### ISSUE TITLE
Several things evaluated as lists panic

### ISSUE THREAD

**Issue by biiwide** [eigenhombre/l1#28]
It probably should return an instead.
```
> (t)
panic: interface conversion: main.Sexpr is main.Atom, not *main.Builtin

goroutine 1 [running]:
main.applyFn(0x1112ca8, 0xc000096d30, 0x11c7550, 0x0, 0x0, 0x0, 0x0, 0xc000096d20, 0xc000092e68)
	/Users/tcushman/git/l1/lisp.go:103 +0x155
main.(*ConsCell).Eval(0xc0000c2ba0, 0xc000096d20, 0x2, 0x11c7550, 0xc0000c2ba0, 0x10490c5)
	/Users/tcushman/git/l1/lisp.go:138 +0x3cb
main.evalExprs(0xc000096d10, 0x1, 0x1, 0xc000098210, 0x0, 0x1)
	/Users/tcushman/git/l1/main.go:26 +0xbe
main.repl(0xc000098210, 0x0)
	/Users/tcushman/git/l1/main.go:72 +0x27e
main.main()
	/Users/tcushman/git/l1/main.go:86 +0x4a
```

**Comment by biiwide** [comment]
Evaluating the null list triggers similar behavior:
```
> (())
panic: interface conversion: main.Sexpr is *main.ConsCell, not *main.Builtin

goroutine 1 [running]:
main.applyFn(0x1112c48, 0x0, 0x11c7550, 0x0, 0x0, 0x0, 0x0, 0xc000010380, 0xc00007ce68)
	/Users/tcushman/git/l1/lisp.go:103 +0x155
main.(*ConsCell).Eval(0xc00006a020, 0xc000010380, 0x3, 0x11c7550, 0xc00006a020, 0x10490c5)
	/Users/tcushman/git/l1/lisp.go:138 +0x3cb
main.evalExprs(0xc000010370, 0x1, 0x1, 0xc000100210, 0x0, 0x1)
	/Users/tcushman/git/l1/main.go:26 +0xbe
main.repl(0xc000100210, 0x0)
	/Users/tcushman/git/l1/main.go:72 +0x27e
main.main()
	/Users/tcushman/git/l1/main.go:86 +0x4a
```

**Comment by biiwide** [comment]
... and numbers:
```
> (1)
panic: interface conversion: main.Sexpr is main.Number, not *main.Builtin

goroutine 1 [running]:
main.applyFn(0x1112d08, 0xc0000c2060, 0x11c7550, 0x0, 0x0, 0x0, 0x0, 0xc000098370, 0xc000094e68)
	/Users/tcushman/git/l1/lisp.go:103 +0x155
main.(*ConsCell).Eval(0xc0000c2040, 0xc000098370, 0x2, 0x11c7550, 0xc0000c2040, 0x10490c5)
	/Users/tcushman/git/l1/lisp.go:138 +0x3cb
main.evalExprs(0xc000098360, 0x1, 0x1, 0xc00009a210, 0x0, 0x1)
	/Users/tcushman/git/l1/main.go:26 +0xbe
main.repl(0xc00009a210, 0x0)
	/Users/tcushman/git/l1/main.go:72 +0x27e
main.main()
	/Users/tcushman/git/l1/main.go:86 +0x4a
```

**Comment by eigenhombre** [comment]
Nice! Thanks @biiwide for the reports!
